### ISSUE TITLE
Is there any other alternatives for this plugin?

### ISSUE THREAD

**Issue by WuglyakBolgoink** [thedracle/cordova-android-chromeview#16]

**Comment by thedracle** [comment]
Since Android 4.4, the basic WebView in Android has been based on Chromium, so most of the original intent of this is defunct.

If you still want to bundle Chromium for stability purposes, for consistency across different versions of Android, or to support Chrome features < 4.4, I'm not really aware of other work that has been done to implement this, and it has been a very long time since I have had a reason to maintain it.
